# Demo: Concatenation-Fusion Skin Lesion Pipeline

This notebook demonstrates the complete workflow using **concatenation fusion** for:

1. **MobileViT + BioClinicalBERT concat**
2. **ResNet50 + BioClinicalBERT concat**

For each backbone, the notebook shows how to run:

- Hyperparameter tuning with Optuna/TPE
- PAD-UFES closed-set training using all three text combinations:
  - `text_full`
  - `text_core`
  - `text_missing_explicit`
- Direct closed-set generalization to target datasets
- DANN domain adaptation
- Energy-based open-world evaluation
- Result collection and printed summary tables

Long training commands are controlled by `RUN_COMMANDS`. Keep it `False` to preview commands; set it to `True` to run.

## 1. Imports and notebook controls

In [2]:
from __future__ import annotations

import json
import re
import shutil
import subprocess
import sys
from pathlib import Path
from typing import Iterable

import pandas as pd
import numpy as np

pd.set_option("display.max_columns", 100)
pd.set_option("display.width", 180)

# Set True when ready to run tuning/training/evaluation.
RUN_COMMANDS = True

# Print every command before running.
PRINT_COMMANDS = True

# Stop immediately if a subprocess fails.
CHECK_SUBPROCESS = True

# N_TRIALS = 10          
# TRIAL_EPOCHS = 3      
# CLOSED_SET_EPOCHS = 50
# DANN_EPOCHS = 20

N_TRIALS = 2
TRIAL_EPOCHS = 1
CLOSED_SET_EPOCHS = 1
DANN_EPOCHS = 1

## 2. Project/package setup

Your scripts use package-relative imports such as `from .datasets import ...`, so the safest way to run them is as modules:

```bash
python -m your_package.train_closed_set
```

Update `PACKAGE_NAME` and `PROJECT_ROOT`.

In [3]:
PROJECT_ROOT = Path(r"D:/Deep Learning/skin_lesion_openworld/skin_lesion_openworld")

# Your .py files are directly inside:
# D:/Deep Learning/skin_lesion_openworld/skin_lesion_openworld/src
PACKAGE_NAME = "src"

PACKAGE_ROOT = PROJECT_ROOT / PACKAGE_NAME

# Keep this True because your scripts use relative imports:
# from .datasets import ...
RUN_AS_MODULE = True

if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

print("PROJECT_ROOT:", PROJECT_ROOT)
print("PACKAGE_ROOT:", PACKAGE_ROOT)
print("RUN_AS_MODULE:", RUN_AS_MODULE)

PROJECT_ROOT: D:\Deep Learning\skin_lesion_openworld\skin_lesion_openworld
PACKAGE_ROOT: D:\Deep Learning\skin_lesion_openworld\skin_lesion_openworld\src
RUN_AS_MODULE: True

## 3. Required files and concatenation-fusion validation

This checks that the concat model families are exposed:

- `mobilevit_concat`
- `resnet50_concat`

In [4]:
REQUIRED_FILES = [
    "config.py",
    "preprocessing.py",
    "datasets.py",
    "models.py",
    "metrics.py",
    "transforms.py",
    "visualization.py",
    "utils.py",
    "train_closed_set.py",
    "evaluate_closed_set_transfer.py",
    "train_dann.py",
    "evaluate_openworld.py",
    "tune_hyperparameters.py",
]

def package_file(name: str) -> Path:
    return PACKAGE_ROOT / name if RUN_AS_MODULE else PROJECT_ROOT / name

def validate_project_files() -> None:
    missing = [name for name in REQUIRED_FILES if not package_file(name).exists()]
    if missing:
        raise FileNotFoundError(
            "Missing required files: "
            + ", ".join(missing)
            + f"\nChecked: {PACKAGE_ROOT if RUN_AS_MODULE else PROJECT_ROOT}"
        )

    models_text = package_file("models.py").read_text(encoding="utf-8")
    required_model_markers = [
        "ConcatenationFusionHead",
        "mobilevit_concat",
        "resnet50_concat",
    ]
    missing_model_markers = [
        marker for marker in required_model_markers if marker not in models_text
    ]
    if missing_model_markers:
        raise ValueError(
            "models.py is not concat-ready. Missing: "
            + ", ".join(missing_model_markers)
            + "\nReplace models.py with the concat-ready models_corrected.py."
        )

    for script_name in [
        "train_closed_set.py",
        "train_dann.py",
        "evaluate_openworld.py",
        "evaluate_closed_set_transfer.py",
        "tune_hyperparameters.py",
    ]:
        text = package_file(script_name).read_text(encoding="utf-8")
        for model_key in ["mobilevit_concat", "resnet50_concat"]:
            if model_key not in text:
                raise ValueError(
                    f"{script_name} does not expose {model_key}. "
                    "Use the corrected concat-ready version."
                )

    print("Project files found and concatenation fusion is exposed.")

# Run this after setting PROJECT_ROOT and PACKAGE_NAME.
validate_project_files()

Project files found and concatenation fusion is exposed.

## 4. Dataset paths and output locations

In [30]:
# ----------------------------
# Raw PAD-UFES paths
# ----------------------------
PADUFES_CSV = Path(r"D:/Deep Learning/metadata.csv")
PADUFES_IMAGE_DIR = Path(r"D:/Deep Learning/images")

# ----------------------------
# Standardized split CSV
# ----------------------------
OUTPUT_ROOT = Path(r"D:/Deep Learning/output_concat_demo")
STANDARDIZED_DIR = OUTPUT_ROOT / "standardized"
STANDARDIZED_CSV = STANDARDIZED_DIR / "all_preprocessed_splits_standardized_text.csv"

# ----------------------------
# Target image roots
# ----------------------------
SOURCE_DATASET = "PAD-UFES-20"

TARGETS = {
    "ISIC 2019": [
        Path(r"D:/Deep Learning/ISIC_2019_Training_Input"),
        Path(r"D:/Deep Learning/ISIC_2019_Test_Input"),
    ],
    "MCR-SL": [
        Path(r"D:/Deep Learning/MCR-SL_dataset/dermoscopic"),
        Path(r"D:/Deep Learning/MCR-SL_dataset/images"),
        Path(r"D:/Deep Learning/MCR-SL_dataset"),
    ],
}

# ----------------------------
# Optional raw metadata paths for preprocessing
# ----------------------------
ISIC_TRAIN_GT = Path(r"D:/Deep Learning/ISIC_2019_Training_GroundTruth.csv")
ISIC_TRAIN_META = Path(r"D:/Deep Learning/ISIC_2019_Training_Metadata.csv")
ISIC_TEST_GT = Path(r"D:/Deep Learning/ISIC_2019_Test_GroundTruth.csv")
ISIC_TEST_META = Path(r"D:/Deep Learning/ISIC_2019_Test_Metadata.csv")

MCR_UNIFIED_XLSX = Path(r"D:/Deep Learning/MCR-SL_dataset/unified_diagnosis.xlsx")
MCR_LESION_XLSX = Path(r"D:/Deep Learning/MCR-SL_dataset/lesion.xlsx")
MCR_SUBJECT_XLSX = Path(r"D:/Deep Learning/MCR-SL_dataset/subject.xlsx")
MCR_IMAGE_XLSX = Path(r"D:/Deep Learning/MCR-SL_dataset/image.xlsx")
MCR_DERM_XLSX = Path(r"D:/Deep Learning/MCR-SL_dataset/dermatology_diagnosis.xlsx")
MCR_HISTO_XLSX = Path(r"D:/Deep Learning/MCR-SL_dataset/histopathology_diagnosis.xlsx")

# ----------------------------
# Output folders
# ----------------------------
TUNING_OUT = OUTPUT_ROOT / "01_tuning"
CLOSED_SET_OUT = OUTPUT_ROOT / "02_closed_set"
DIRECT_TRANSFER_OUT = OUTPUT_ROOT / "03_direct_transfer"
DANN_OUT = OUTPUT_ROOT / "04_dann"
OPENWORLD_OUT = OUTPUT_ROOT / "05_open_world"

TEXT_COLS = ["text_full", "text_core", "text_missing_explicit"]

# Short demo settings. Increase for final runs.
N_TRIALS = 10
TRIAL_EPOCHS = 3
CLOSED_SET_EPOCHS = 30
DANN_EPOCHS = 15
BATCH_SIZE_FALLBACK = 16
ENERGY_TEMPERATURE = 1.0

OUTPUT_ROOT.mkdir(parents=True, exist_ok=True)
print("Output root:", OUTPUT_ROOT)

Output root: D:\Deep Learning\output_concat_demo

## 5. Command helpers

In [31]:
def module_or_script_cmd(module_name: str) -> list[str]:
    if RUN_AS_MODULE:
        return [sys.executable, "-m", f"{PACKAGE_NAME}.{module_name}"]
    return [sys.executable, str(PROJECT_ROOT / f"{module_name}.py")]

import os
import subprocess

def run_command(cmd: list[str], cwd: Path | None = None) -> subprocess.CompletedProcess | None:
    if PRINT_COMMANDS:
        print("\n" + "=" * 120)
        print(" ".join(map(str, cmd)))
        print("=" * 120)

    if not RUN_COMMANDS:
        print("RUN_COMMANDS=False, command preview only.")
        return None

    env = os.environ.copy()

    # Important:
    # PROJECT_ROOT lets Python run modules as src.train_closed_set.
    # PACKAGE_ROOT lets absolute imports like "from config import ..." work.

    extra_python_paths = [
        str(PACKAGE_ROOT),  # src folder first, so "from config import ..." finds src/config.py
        str(PROJECT_ROOT),
    ]

    old_pythonpath = env.get("PYTHONPATH", "")
    env["PYTHONPATH"] = os.pathsep.join(
        extra_python_paths + ([old_pythonpath] if old_pythonpath else [])
    )

    old_pythonpath = env.get("PYTHONPATH", "")
    env["PYTHONPATH"] = os.pathsep.join(
        extra_python_paths + ([old_pythonpath] if old_pythonpath else [])
    )

    result = subprocess.run(
        list(map(str, cmd)),
        cwd=str(cwd or PROJECT_ROOT),
        check=False,
        text=True,
        capture_output=True,
        env=env,
    )

    print("\nSTDOUT:")
    print(result.stdout)

    print("\nSTDERR:")
    print(result.stderr)

    if CHECK_SUBPROCESS and result.returncode != 0:
        raise subprocess.CalledProcessError(
            result.returncode,
            result.args,
            output=result.stdout,
            stderr=result.stderr,
        )

    return result

def read_json(path: Path) -> dict:
    with Path(path).open("r", encoding="utf-8") as f:
        return json.load(f)

def find_first_existing(paths: Iterable[Path]) -> Path | None:
    for path in paths:
        if path.exists():
            return path
    return None

def safe_read_csv(path: Path) -> pd.DataFrame:
    if not path.exists():
        return pd.DataFrame()
    return pd.read_csv(path)

## 6. Optional preprocessing

Run this only if you still need to create `all_preprocessed_splits_standardized_text.csv`.

If the CSV already exists, skip this section.

In [7]:
# Optional preprocessing.
# Uncomment and adjust imports/package name if needed.
#
# from skin_lesion_owda.preprocessing import prepare_all_standardized_splits
#
# STANDARDIZED_DIR.mkdir(parents=True, exist_ok=True)
#
# standardized_df = prepare_all_standardized_splits(
#     output_dir=STANDARDIZED_DIR,
#     padufes_csv=PADUFES_CSV,
#     isic_train_groundtruth_csv=ISIC_TRAIN_GT,
#     isic_train_metadata_csv=ISIC_TRAIN_META,
#     isic_test_groundtruth_csv=ISIC_TEST_GT,
#     isic_test_metadata_csv=ISIC_TEST_META,
#     mcr_unified_xlsx=MCR_UNIFIED_XLSX,
#     mcr_lesion_xlsx=MCR_LESION_XLSX,
#     mcr_subject_xlsx=MCR_SUBJECT_XLSX,
#     mcr_image_xlsx=MCR_IMAGE_XLSX,
#     mcr_dermatology_diagnosis_xlsx=MCR_DERM_XLSX,
#     mcr_histopathology_diagnosis_xlsx=MCR_HISTO_XLSX,
#     write_individual_csvs=True,
#     print_reports=True,
# )
#
# display(standardized_df.head())
# display(standardized_df.groupby(["dataset", "split", "known_unknown"]).size())

## 7. Hyperparameter tuning helpers

Each backbone is tuned separately. The tuner searches over the three text combinations.

In [32]:
def tune_closed_set(model_family: str) -> Path:
    out_dir = TUNING_OUT / model_family / "closed_set"

    cmd = [
        *module_or_script_cmd("tune_hyperparameters"),
        "--study", "closed_set",
        "--padufes-csv", str(PADUFES_CSV),
        "--padufes-image-dir", str(PADUFES_IMAGE_DIR),
        "--output-dir", str(out_dir),
        "--n-trials", str(N_TRIALS),
        "--trial-epochs", str(TRIAL_EPOCHS),
        "--model-families", model_family,
        "--text-cols", *TEXT_COLS,
        "--batch-sizes", "8", "16", "32",
        "--fusion-dims", "128", "256", "384", "512",
        "--use-sampler",
        "--use-weighted-loss",
    ]

    run_command(cmd)
    return out_dir

def load_best_hyperparameters(tuning_dir: Path) -> dict:
    path = tuning_dir / "best_hyperparameters.json"
    if not path.exists():
        print("Best hyperparameter file not found yet:", path)
        return {}

    best = read_json(path)
    print(json.dumps(best, indent=2))
    return best.get("best_params", {})

def print_tuning_trials(tuning_dir: Path):
    trials_path = tuning_dir / "all_trials.csv"
    trials = safe_read_csv(trials_path)
    if trials.empty:
        print("No tuning trials found yet:", trials_path)
        return

    display(trials.sort_values("value", ascending=False).head(10))

## 8. Apply selected tuning results to `config.py`

The training scripts read some values from `config.py`.

This helper updates common defaults before launching subprocess training. It creates a backup named `config.py.demo_backup`.

Applied values when present:

- `lr`
- `weight_decay`
- `fusion_dim`
- `num_heads`
- `balance_beta`

`batch_size` is passed directly through CLI.

In [33]:
def update_config_default(config_text: str, key: str, value) -> str:
    pattern = rf"(^\s*{re.escape(key)}\s*:\s*[^=]+=\s*)(.+?)(\s*(?:#.*)?$)"
    replacement_value = repr(value)

    updated, n = re.subn(
        pattern,
        rf"\g<1>{replacement_value}\g<3>",
        config_text,
        flags=re.MULTILINE,
    )

    if n == 0:
        print(f"Warning: did not find config key `{key}`.")
    return updated

def apply_best_params_to_config(best_params: dict):
    if not best_params:
        print("No best params supplied; using existing config.py.")
        return

    config_path = package_file("config.py")
    backup_path = config_path.with_suffix(".py.demo_backup")

    if not backup_path.exists():
        shutil.copy2(config_path, backup_path)
        print("Created config backup:", backup_path)

    text = config_path.read_text(encoding="utf-8")

    for key in ["lr", "weight_decay", "fusion_dim", "num_heads", "balance_beta"]:
        if key in best_params:
            text = update_config_default(text, key, best_params[key])

    config_path.write_text(text, encoding="utf-8")
    print("Updated config.py with selected tuning values.")

def batch_size_from_params(best_params: dict) -> int:
    return int(best_params.get("batch_size", BATCH_SIZE_FALLBACK))

## 9. Pipeline command builders

In [34]:
def closed_set_checkpoint(model_family: str, text_col: str) -> Path:
    candidates = [
        CLOSED_SET_OUT / model_family / text_col / "best.pt",
        CLOSED_SET_OUT / model_family / text_col / f"{model_family}_{text_col}_best.pt",
    ]

    found = find_first_existing(candidates)
    if found is not None:
        return found

    search_root = CLOSED_SET_OUT / model_family / text_col
    matches = list(search_root.rglob("*best*.pt")) if search_root.exists() else []
    if matches:
        return matches[0]

    return candidates[0]

def dann_checkpoint(model_family: str, text_col: str, target_dataset: str) -> Path:
    target_name = target_dataset.replace("/", "_").replace("\\", "_").replace(" ", "_").replace("-", "_")

    candidates = [
        DANN_OUT / model_family / text_col / target_name / "best_dann.pt",
        DANN_OUT / model_family / text_col / target_dataset / "best_dann.pt",
    ]

    found = find_first_existing(candidates)
    if found is not None:
        return found

    base = DANN_OUT / model_family / text_col
    matches = list(base.rglob("*best*dann*.pt")) if base.exists() else []
    if matches:
        return matches[0]

    return candidates[0]

def run_closed_set_training(model_family: str, batch_size: int):
    cmd = [
        *module_or_script_cmd("train_closed_set"),
        "--padufes-csv", str(PADUFES_CSV),
        "--padufes-image-dir", str(PADUFES_IMAGE_DIR),
        "--output-dir", str(CLOSED_SET_OUT),
        "--model-family", model_family,
        "--text-col", "all",
        "--batch-size", str(batch_size),
        "--epochs", str(CLOSED_SET_EPOCHS),
    ]
    run_command(cmd)

def run_direct_generalization(
    model_family: str,
    text_col: str,
    target_dataset: str,
    target_roots: list[Path],
    batch_size: int,
):
    ckpt = closed_set_checkpoint(model_family, text_col)

    cmd = [
        *module_or_script_cmd("evaluate_closed_set_transfer"),
        "--standardized-csv", str(STANDARDIZED_CSV),
        "--target-dataset", target_dataset,
        "--target-image-roots", *map(str, target_roots),
        "--checkpoint", str(ckpt),
        "--output-dir", str(DIRECT_TRANSFER_OUT),
        "--model-family", model_family,
        "--text-col", text_col,
        "--batch-size", str(batch_size),
    ]
    run_command(cmd)

def run_dann(
    model_family: str,
    text_col: str,
    target_dataset: str,
    target_roots: list[Path],
    batch_size: int,
):
    ckpt = closed_set_checkpoint(model_family, text_col)

    cmd = [
        *module_or_script_cmd("train_dann"),
        "--standardized-csv", str(STANDARDIZED_CSV),
        "--source-dataset", "PAD-UFES",
        "--target-dataset", target_dataset,
        "--source-image-roots", str(PADUFES_IMAGE_DIR),
        "--target-image-roots", *map(str, target_roots),
        "--checkpoint", str(ckpt),
        "--output-dir", str(DANN_OUT),
        "--model-family", model_family,
        "--text-col", text_col,
        "--batch-size", str(batch_size),
        "--epochs", str(DANN_EPOCHS),
        "--energy-temperature", str(ENERGY_TEMPERATURE),
    ]
    run_command(cmd)

def run_open_world(
    model_family: str,
    text_col: str,
    target_dataset: str,
    target_roots: list[Path],
    batch_size: int,
):
    ckpt = dann_checkpoint(model_family, text_col, target_dataset)

    cmd = [
        *module_or_script_cmd("evaluate_openworld"),
        "--standardized-csv", str(STANDARDIZED_CSV),
        "--target-dataset", target_dataset,
        "--target-image-roots", *map(str, target_roots),
        "--checkpoint", str(ckpt),
        "--output-dir", str(OPENWORLD_OUT),
        "--model-family", model_family,
        "--text-col", text_col,
        "--batch-size", str(batch_size),
        "--energy-temperature", str(ENERGY_TEMPERATURE),
        "--dann",
    ]
    run_command(cmd)

## 10. Result collection helpers

In [35]:
def collect_csv_files(root: Path, patterns: list[str]) -> pd.DataFrame:
    rows = []

    for pattern in patterns:
        for path in root.rglob(pattern) if root.exists() else []:
            try:
                df = pd.read_csv(path)
                if df.empty:
                    continue
                df["source_file"] = str(path)
                rows.append(df)
            except Exception as exc:
                print("Could not read", path, "because", exc)

    if not rows:
        return pd.DataFrame()

    return pd.concat(rows, ignore_index=True, sort=False)

def collect_json_metrics(root: Path, patterns: list[str]) -> pd.DataFrame:
    rows = []

    for pattern in patterns:
        for path in root.rglob(pattern) if root.exists() else []:
            try:
                data = read_json(path)
                flat = {"source_file": str(path)}

                def flatten(prefix, obj):
                    if isinstance(obj, dict):
                        for k, v in obj.items():
                            flatten(f"{prefix}{k}.", v)
                    elif isinstance(obj, (int, float, str, bool)) or obj is None:
                        flat[prefix[:-1]] = obj

                flatten("", data)
                rows.append(flat)
            except Exception as exc:
                print("Could not read", path, "because", exc)

    return pd.DataFrame(rows)

def choose_best_row(df: pd.DataFrame):
    metric_priority = [
        "test_macro_f1",
        "test_f1_macro",
        "macro_f1",
        "f1_macro",
        "val_macro_f1",
        "val_f1_macro",
        "accuracy",
        "test_accuracy",
    ]

    metric_col = None
    for col in metric_priority:
        if col in df.columns:
            metric_col = col
            break

    if metric_col is None:
        numeric_cols = df.select_dtypes(include="number").columns.tolist()
        if not numeric_cols:
            raise ValueError("No numeric metric column found in summary CSV.")
        metric_col = numeric_cols[0]

    best_idx = df[metric_col].astype(float).idxmax()
    return df.loc[[best_idx]].copy(), metric_col


def print_closed_set_results(model_family: str):
    print(f"\nClosed-set best result for {model_family}")

    # Load only summary CSVs, not classification reports.
    summary_files = list((CLOSED_SET_OUT).glob("closed_set_summary.csv"))
    summary_files += list((CLOSED_SET_OUT).glob("*_closed_set_summary.csv"))

    # Also check model-specific nested folders, just in case.
    summary_files += list((CLOSED_SET_OUT / model_family).rglob("closed_set_summary.csv"))
    summary_files += list((CLOSED_SET_OUT / model_family).rglob("*_closed_set_summary.csv"))

    summary_files = sorted(set(summary_files))

    if not summary_files:
        print("No closed-set summary CSV found yet.")
        return pd.DataFrame()

    rows = []
    for path in summary_files:
        df = pd.read_csv(path)
        if not df.empty:
            df["source_file"] = str(path)
            rows.append(df)

    if not rows:
        print("Closed-set summary files were found but empty.")
        return pd.DataFrame()

    summary_df = pd.concat(rows, ignore_index=True, sort=False)

    best_df, metric_col = choose_best_row(summary_df)

    best_out = CLOSED_SET_OUT / model_family / "best_closed_set_result.csv"
    best_out.parent.mkdir(parents=True, exist_ok=True)
    best_df.to_csv(best_out, index=False)

    print(f"Selected best row using metric: {metric_col}")
    print(f"Saved best closed-set result to: {best_out}")

    display(best_df)

    return best_df

def print_direct_transfer_results(model_family: str):
    print(f"\nDirect generalization results for {model_family}")
    root = DIRECT_TRANSFER_OUT / model_family
    df = collect_csv_files(root, ["*summary*.csv", "*classification_report.csv"])
    if df.empty:
        print("No direct transfer summaries/reports found yet.")
    else:
        display(df.head(30))

def _select_best_metric_column(df: pd.DataFrame):
    metric_priority = [
        "test_macro_f1",
        "target_test_known.macro_f1",
        "target_test_known_macro_f1",
        "openworld_target_test.open_macro_f1",
        "open_macro_f1",
        "macro_f1",
        "f1_macro",
        "weighted_f1",
        "accuracy",
        "open_accuracy",
    ]

    for col in metric_priority:
        if col in df.columns:
            return col

    numeric_cols = df.select_dtypes(include="number").columns.tolist()
    return numeric_cols[0] if numeric_cols else None


def _display_best_summary(
    *,
    title: str,
    root: Path,
    output_name: str,
    patterns: list[str] | None = None,
):
    print(f"\n{title}")

    patterns = patterns or ["*summary*.csv"]
    df = collect_csv_files(root, patterns)

    if df.empty:
        print(f"No summary CSV found under: {root}")
        return pd.DataFrame()

    metric_col = _select_best_metric_column(df)

    if metric_col is None:
        print("Summary found, but no numeric metric column was available.")
        display(df.head(10))
        return df

    best_idx = df[metric_col].astype(float).idxmax()
    best_df = df.loc[[best_idx]].copy()

    out_path = root / output_name
    out_path.parent.mkdir(parents=True, exist_ok=True)
    best_df.to_csv(out_path, index=False)

    print(f"Selected best row using metric: {metric_col}")
    print(f"Saved: {out_path}")

    display(best_df)
    return best_df


def print_direct_transfer_results(model_family: str):
    root = DIRECT_TRANSFER_OUT / model_family

    return _display_best_summary(
        title=f"Best direct generalization result for {model_family}",
        root=root,
        output_name="best_direct_transfer_result.csv",
        patterns=["*summary*.csv"],
    )


def print_dann_results(model_family: str):
    root = DANN_OUT / model_family

    return _display_best_summary(
        title=f"Best DANN result for {model_family}",
        root=root,
        output_name="best_dann_result.csv",
        patterns=["*summary*.csv"],
    )


def print_open_world_results(model_family: str):
    print(f"\nBest open-world result for {model_family}")

    root = OPENWORLD_OUT / model_family

    # Prefer summary CSVs if present.
    csv_df = collect_csv_files(root, ["*summary*.csv"])

    if not csv_df.empty:
        metric_col = _select_best_metric_column(csv_df)

        if metric_col is not None:
            best_idx = csv_df[metric_col].astype(float).idxmax()
            best_df = csv_df.loc[[best_idx]].copy()

            out_path = root / "best_open_world_result.csv"
            out_path.parent.mkdir(parents=True, exist_ok=True)
            best_df.to_csv(out_path, index=False)

            print(f"Selected best CSV row using metric: {metric_col}")
            print(f"Saved: {out_path}")
            display(best_df)
            return best_df

    # Fallback to JSON metrics.
    json_df = collect_json_metrics(root, ["*metrics*.json", "openworld_metrics.json"])

    if json_df.empty:
        print("No open-world summary or metrics files found yet.")
        return pd.DataFrame()

    important_cols = [
        c for c in json_df.columns
        if any(key in c for key in [
            "open_macro_f1",
            "open_weighted_f1",
            "unknown_auroc",
            "unknown_recall",
            "unknown_f1",
            "oscr",
            "threshold",
            "scoring_method",
        ])
    ]

    metric_col = _select_best_metric_column(json_df[important_cols]) if important_cols else None

    if metric_col is None:
        display(json_df.head(10))
        return json_df

    best_idx = json_df[metric_col].astype(float).idxmax()
    best_df = json_df.loc[[best_idx]].copy()

    out_path = root / "best_open_world_result.csv"
    out_path.parent.mkdir(parents=True, exist_ok=True)
    best_df.to_csv(out_path, index=False)

    print(f"Selected best JSON row using metric: {metric_col}")
    print(f"Saved: {out_path}")

    cols_to_show = ["source_file", *important_cols]
    cols_to_show = [c for c in cols_to_show if c in best_df.columns]
    display(best_df[cols_to_show])

    return best_df

def print_all_results(model_family: str):
    print_closed_set_results(model_family)
    print_direct_transfer_results(model_family)
    print_dann_results(model_family)
    print_open_world_results(model_family)

## 11. Full pipeline function

In [37]:
def tune_closed_set(model_family: str, n_trials: int, trial_epochs: int) -> Path:
    out_dir = TUNING_OUT / model_family / "closed_set"

    cmd = [
        *module_or_script_cmd("tune_hyperparameters"),
        "--study", "closed_set",
        "--padufes-csv", str(PADUFES_CSV),
        "--padufes-image-dir", str(PADUFES_IMAGE_DIR),
        "--output-dir", str(out_dir),
        "--n-trials", str(n_trials),
        "--trial-epochs", str(trial_epochs),
        "--model-families", model_family,
        "--text-cols", *TEXT_COLS,
        "--batch-sizes", "8", "16", "32",
        "--fusion-dims", "128", "256", "384", "512",
        "--use-sampler",
        "--use-weighted-loss",
    ]

    run_command(cmd)
    return out_dir


def run_closed_set_training(model_family: str, batch_size: int, epochs: int):
    cmd = [
        *module_or_script_cmd("train_closed_set"),
        "--padufes-csv", str(PADUFES_CSV),
        "--padufes-image-dir", str(PADUFES_IMAGE_DIR),
        "--output-dir", str(CLOSED_SET_OUT),
        "--model-family", model_family,
        "--text-col", "all",
        "--batch-size", str(batch_size),
        "--epochs", str(epochs),
    ]
    run_command(cmd)


def run_dann(
    model_family: str,
    text_col: str,
    target_dataset: str,
    target_roots: list[Path],
    batch_size: int,
    epochs: int,
):
    ckpt = closed_set_checkpoint(model_family, text_col)

    cmd = [
        *module_or_script_cmd("train_dann"),
        "--standardized-csv", str(STANDARDIZED_CSV),
        "--source-dataset", SOURCE_DATASET,
        "--target-dataset", target_dataset,
        "--source-image-roots", str(PADUFES_IMAGE_DIR),
        "--target-image-roots", *map(str, target_roots),
        "--checkpoint", str(ckpt),
        "--output-dir", str(DANN_OUT),
        "--model-family", model_family,
        "--text-col", text_col,
        "--batch-size", str(batch_size),
        "--epochs", str(epochs),
        "--energy-temperature", str(ENERGY_TEMPERATURE),
    ]
    run_command(cmd)

def validate_standardized_dataset_names():
    df = pd.read_csv(STANDARDIZED_CSV)

    available = set(df["dataset"].dropna().unique())
    required = {SOURCE_DATASET, *TARGETS.keys()}
    missing = required - available

    if missing:
        raise ValueError(
            "Dataset name mismatch in standardized CSV.\n"
            f"Missing requested names: {sorted(missing)}\n"
            f"Available names: {sorted(available)}\n\n"
            "Use the exact names from the standardized CSV."
        )

    print("Standardized dataset names OK:")
    print(sorted(available))

def run_full_concat_pipeline(
    model_family: str,
    n_trials: int = 10,
    trial_epochs: int = 3,
    closed_set_epochs: int = 50,
    dann_epochs: int = 20,
):
    assert model_family in {"mobilevit_concat", "resnet50_concat"}

    print("\n" + "#" * 120)
    print(f"STARTING PIPELINE: {model_family}")
    print("#" * 120)

    print(
        f"Settings: n_trials={n_trials}, "
        f"trial_epochs={trial_epochs}, "
        f"closed_set_epochs={closed_set_epochs}, "
        f"dann_epochs={dann_epochs}"
    )

    # 1. Hyperparameter tuning.
    tuning_dir = tune_closed_set(
        model_family=model_family,
        n_trials=n_trials,
        trial_epochs=trial_epochs,
    )
    best_params = load_best_hyperparameters(tuning_dir)
    print_tuning_trials(tuning_dir)

    # 2. Apply best parameters where scripts consume config.py defaults.
    apply_best_params_to_config(best_params)
    batch_size = batch_size_from_params(best_params)
    print(f"\nUsing batch size for {model_family}: {batch_size}")

    # 3. Closed-set training on all three text combinations.
    run_closed_set_training(
        model_family=model_family,
        batch_size=batch_size,
        epochs=closed_set_epochs,
    )

    # 4. Print closed-set results.
    print_closed_set_results(model_family)

    # 5. Direct transfer, DANN, and energy-based open-world evaluation.
    for text_col in TEXT_COLS:
        for target_dataset, target_roots in TARGETS.items():
            print("\n" + "-" * 120)
            print(f"{model_family} | {text_col} | target={target_dataset}")
            print("-" * 120)

            run_direct_generalization(
                model_family=model_family,
                text_col=text_col,
                target_dataset=target_dataset,
                target_roots=target_roots,
                batch_size=batch_size,
            )

            run_dann(
                model_family=model_family,
                text_col=text_col,
                target_dataset=target_dataset,
                target_roots=target_roots,
                batch_size=batch_size,
                epochs=dann_epochs,
            )

            run_open_world(
                model_family=model_family,
                text_col=text_col,
                target_dataset=target_dataset,
                target_roots=target_roots,
                batch_size=batch_size,
            )

    # 6. Print final summaries.
    print_all_results(model_family)

    print("\n" + "#" * 120)
    print(f"FINISHED PIPELINE: {model_family}")
    print("#" * 120)

In [28]:
validate_standardized_dataset_names()

Standardized dataset names OK:
['ISIC 2019', 'MCR-SL', 'PAD-UFES-20']

C:\Users\Nebula PC\AppData\Local\Temp\ipykernel_29264\2003150044.py:66: DtypeWarning: Columns (12,14,15,16,17,18,22,23,24,25,26,27,33,34,35,37,38,39,40,41,42,43,44,45,46,47,48,49,50) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(STANDARDIZED_CSV)

# Part A — MobileViT concatenation

This block performs:

- Hyperparameter tuning for `mobilevit_concat`
- Closed-set training using all three text combinations
- Direct generalization
- DANN
- Energy-based open-world evaluation
- Final open-world result printing

In [ ]:
# validate_project_files()
run_full_concat_pipeline(
    model_family="mobilevit_concat",
    n_trials=2,
    trial_epochs=1,
    closed_set_epochs=1,
    dann_epochs=1,
)

########################################################################################################################
STARTING PIPELINE: mobilevit_concat
########################################################################################################################
Settings: n_trials=2, trial_epochs=1, closed_set_epochs=1, dann_epochs=1

========================================================================================================================
d:\anaconda3\envs\pytorch\python.exe -m src.tune_hyperparameters --study closed_set --padufes-csv D:\Deep Learning\metadata.csv --padufes-image-dir D:\Deep Learning\images --output-dir D:\Deep Learning\output_concat_demo\01_tuning\mobilevit_concat\closed_set --n-trials 2 --trial-epochs 1 --model-families mobilevit_concat --text-cols text_full text_core text_missing_explicit --batch-sizes 8 16 32 --fusion-dims 128 256 384 512 --use-sampler --use-weighted-loss
========================================================================================================================

STDOUT:
Imported config module: D:\Deep Learning\skin_lesion_openworld\skin_lesion_openworld\config.py
Best value: 0.28178899751933456
Best params:
  lr: 8.46800857524833e-06
  weight_decay: 0.0007114476009343421
  fusion_dim: 128
  balance_beta: 0.9057502776046518
  model_family: mobilevit_concat
  text_col: text_full
  batch_size: 16
Saved tuning outputs to: D:\Deep Learning\output_concat_demo\01_tuning\mobilevit_concat\closed_set


STDERR:
d:\anaconda3\envs\pytorch\lib\site-packages\optuna\_experimental.py:33: ExperimentalWarning: Argument ``multivariate`` is an experimental feature. The interface can change in the future.
  optuna_warn(
[I 2026-05-31 02:22:48,675] A new study created in memory with name: no-name-3de6dd1c-1098-4e46-9e66-ea542cd886bc
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]
Loading weights: 100%|██████████| 199/199 [00:00<00:00, 33157.21it/s]
[transformers] BertModel LOAD REPORT from: emilyalsentzer/Bio_ClinicalBERT
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |
cls.predictions.decoder.weight             | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
d:\anaconda3\envs\pytorch\lib\site-packages\sklearn\metrics\_ranking.py:424: UndefinedMetricWarning: Only one class is present in y_true. ROC AUC score is not defined in that case.
  warnings.warn(
d:\anaconda3\envs\pytorch\lib\site-packages\sklearn\metrics\_ranking.py:424: UndefinedMetricWarning: Only one class is present in y_true. ROC AUC score is not defined in that case.
  warnings.warn(
[I 2026-05-31 02:23:35,649] Trial 0 finished with value: 0.28178899751933456 and parameters: {'lr': 8.46800857524833e-06, 'weight_decay': 0.0007114476009343421, 'fusion_dim': 128, 'balance_beta': 0.9057502776046518, 'model_family': 'mobilevit_concat', 'text_col': 'text_full', 'batch_size': 16}. Best is trial 0 with value: 0.28178899751933456.

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]
Loading weights: 100%|██████████| 199/199 [00:00<00:00, 22112.13it/s]
[transformers] BertModel LOAD REPORT from: emilyalsentzer/Bio_ClinicalBERT
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |
cls.predictions.decoder.weight             | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
d:\anaconda3\envs\pytorch\lib\site-packages\sklearn\metrics\_ranking.py:424: UndefinedMetricWarning: Only one class is present in y_true. ROC AUC score is not defined in that case.
  warnings.warn(
d:\anaconda3\envs\pytorch\lib\site-packages\sklearn\metrics\_ranking.py:424: UndefinedMetricWarning: Only one class is present in y_true. ROC AUC score is not defined in that case.
  warnings.warn(
[I 2026-05-31 02:24:17,247] Trial 1 finished with value: 0.14033149171270717 and parameters: {'lr': 3.357296705351793e-06, 'weight_decay': 3.5113563139704077e-06, 'fusion_dim': 384, 'balance_beta': 0.9288316848796062, 'model_family': 'mobilevit_concat', 'text_col': 'text_full', 'batch_size': 32}. Best is trial 0 with value: 0.28178899751933456.

{
  "best_value": 0.28178899751933456,
  "best_params": {
    "lr": 8.46800857524833e-06,
    "weight_decay": 0.0007114476009343421,
    "fusion_dim": 128,
    "balance_beta": 0.9057502776046518,
    "model_family": "mobilevit_concat",
    "text_col": "text_full",
    "batch_size": 16
  },
  "best_trial_number": 0,
  "direction": "MAXIMIZE"
}

   number     state     value        lr  weight_decay  fusion_dim  balance_beta      model_family   text_col  batch_size
0       0  COMPLETE  0.281789  0.000008      0.000711         128      0.905750  mobilevit_concat  text_full          16
1       1  COMPLETE  0.140331  0.000003      0.000004         384      0.928832  mobilevit_concat  text_full          32

Updated config.py with selected tuning values.

Using batch size for mobilevit_concat: 16

========================================================================================================================
d:\anaconda3\envs\pytorch\python.exe -m src.train_closed_set --padufes-csv D:\Deep Learning\metadata.csv --padufes-image-dir D:\Deep Learning\images --output-dir D:\Deep Learning\output_concat_demo\02_closed_set --model-family mobilevit_concat --text-col all --batch-size 16 --epochs 1
========================================================================================================================

STDOUT:

================================================================================
Closed-set experiment: model_family=mobilevit_concat, text_col=text_full
================================================================================
{'epoch': 1, 'train_loss': 1.3423703226490298, 'lr': 0.0001, 'val_accuracy': 0.6723404255319149, 'val_macro_precision': 0.3169625246548323, 'val_macro_recall': 0.4542857142857143, 'val_macro_f1': 0.3729699362283633, 'val_weighted_precision': 0.49193419782617814, 'val_weighted_recall': 0.6723404255319149, 'val_weighted_f1': 0.5677263182379128, 'val_loss': 0.9709708054860433, 'val_macro_auc_ovr': nan, 'val_weighted_auc_ovr': 0.8584810929697971, 'val_macro_auc': nan, 'val_weighted_auc': 0.8584810929697971, 'val_auc': nan, 'val_precision_macro': 0.3169625246548323, 'val_recall_macro': 0.4542857142857143, 'val_f1_macro': 0.3729699362283633, 'val_precision_weighted': 0.49193419782617814, 'val_recall_weighted': 0.6723404255319149, 'val_f1_weighted': 0.5677263182379128}
Saved 5 GradCAM++ examples to: D:\Deep Learning\output_concat_demo\02_closed_set\mobilevit_concat\text_full\gradcampp_examples
Saved closed-set outputs to D:\Deep Learning\output_concat_demo\02_closed_set\mobilevit_concat\text_full

================================================================================
Closed-set experiment: model_family=mobilevit_concat, text_col=text_core
================================================================================
{'epoch': 1, 'train_loss': 1.312943022320236, 'lr': 0.0001, 'val_accuracy': 0.6680851063829787, 'val_macro_precision': 0.305140562248996, 'val_macro_recall': 0.45271091113610795, 'val_macro_f1': 0.3629271838751791, 'val_weighted_precision': 0.4937486114671452, 'val_weighted_recall': 0.6680851063829787, 'val_weighted_f1': 0.5670095008247297, 'val_loss': 0.9418902397155762, 'val_macro_auc_ovr': nan, 'val_weighted_auc_ovr': 0.8688580474857505, 'val_macro_auc': nan, 'val_weighted_auc': 0.8688580474857505, 'val_auc': nan, 'val_precision_macro': 0.305140562248996, 'val_recall_macro': 0.45271091113610795, 'val_f1_macro': 0.3629271838751791, 'val_precision_weighted': 0.4937486114671452, 'val_recall_weighted': 0.6680851063829787, 'val_f1_weighted': 0.5670095008247297}
Saved 5 GradCAM++ examples to: D:\Deep Learning\output_concat_demo\02_closed_set\mobilevit_concat\text_core\gradcampp_examples
Saved closed-set outputs to D:\Deep Learning\output_concat_demo\02_closed_set\mobilevit_concat\text_core

================================================================================
Closed-set experiment: model_family=mobilevit_concat, text_col=text_missing_explicit
================================================================================
{'epoch': 1, 'train_loss': 1.4267801892930183, 'lr': 0.0001, 'val_accuracy': 0.6553191489361702, 'val_macro_precision': 0.2403314917127072, 'val_macro_recall': 0.35428571428571426, 'val_macro_f1': 0.2862833795418065, 'val_weighted_precision': 0.4536616903726343, 'val_weighted_recall': 0.6553191489361702, 'val_weighted_f1': 0.5360413671912596, 'val_loss': 1.1169145504633586, 'val_macro_auc_ovr': nan, 'val_weighted_auc_ovr': 0.8455575961478712, 'val_macro_auc': nan, 'val_weighted_auc': 0.8455575961478712, 'val_auc': nan, 'val_precision_macro': 0.2403314917127072, 'val_recall_macro': 0.35428571428571426, 'val_f1_macro': 0.2862833795418065, 'val_precision_weighted': 0.4536616903726343, 'val_recall_weighted': 0.6553191489361702, 'val_f1_weighted': 0.5360413671912596}
Saved 5 GradCAM++ examples to: D:\Deep Learning\output_concat_demo\02_closed_set\mobilevit_concat\text_missing_explicit\gradcampp_examples
Saved closed-set outputs to D:\Deep Learning\output_concat_demo\02_closed_set\mobilevit_concat\text_missing_explicit

Closed-set summary:
       model_family  ... test_f1_weighted
0  mobilevit_concat  ...         0.575260
1  mobilevit_concat  ...         0.576561
2  mobilevit_concat  ...         0.541134

[3 rows x 26 columns]


STDERR:
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]
Loading weights: 100%|██████████| 199/199 [00:00<00:00, 36081.20it/s]
[transformers] BertModel LOAD REPORT from: emilyalsentzer/Bio_ClinicalBERT
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
cls.seq_relationship.weight                | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.predictions.decoder.weight             | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.

train:   0%|          | 0/69 [00:00<?, ?it/s]
train:   1%|▏         | 1/69 [00:00<00:59,  1.13it/s]
train:   3%|▎         | 2/69 [00:01<00:45,  1.48it/s]
train:   4%|▍         | 3/69 [00:01<00:41,  1.61it/s]
train:   6%|▌         | 4/69 [00:02<00:40,  1.62it/s]
train:   7%|▋         | 5/69 [00:03<00:37,  1.73it/s]
train:   9%|▊         | 6/69 [00:03<00:36,  1.72it/s]
train:  10%|█         | 7/69 [00:04<00:34,  1.79it/s]
train:  12%|█▏        | 8/69 [00:04<00:34,  1.76it/s]
train:  13%|█▎        | 9/69 [00:05<00:34,  1.75it/s]
train:  14%|█▍        | 10/69 [00:05<00:33,  1.78it/s]
train:  16%|█▌        | 11/69 [00:06<00:31,  1.81it/s]
train:  17%|█▋        | 12/69 [00:06<00:31,  1.84it/s]
train:  19%|█▉        | 13/69 [00:07<00:30,  1.82it/s]
train:  20%|██        | 14/69 [00:08<00:30,  1.80it/s]
train:  22%|██▏       | 15/69 [00:08<00:29,  1.84it/s]
train:  23%|██▎       | 16/69 [00:09<00:28,  1.86it/s]
train:  25%|██▍       | 17/69 [00:09<00:28,  1.85it/s]
train:  26%|██▌       | 18/69 [00:10<00:27,  1.86it/s]
train:  28%|██▊       | 19/69 [00:10<00:26,  1.92it/s]
train:  29%|██▉       | 20/69 [00:11<00:24,  1.97it/s]
train:  30%|███       | 21/69 [00:11<00:25,  1.85it/s]
train:  32%|███▏      | 22/69 [00:12<00:25,  1.84it/s]
train:  33%|███▎      | 23/69 [00:12<00:25,  1.81it/s]
train:  35%|███▍      | 24/69 [00:13<00:26,  1.69it/s]
train:  36%|███▌      | 25/69 [00:14<00:25,  1.74it/s]
train:  38%|███▊      | 26/69 [00:14<00:24,  1.75it/s]
train:  39%|███▉      | 27/69 [00:15<00:23,  1.79it/s]
train:  41%|████      | 28/69 [00:15<00:22,  1.81it/s]
train:  42%|████▏     | 29/69 [00:16<00:20,  1.98it/s]
train:  43%|████▎     | 30/69 [00:16<00:20,  1.87it/s]
train:  45%|████▍     | 31/69 [00:17<00:20,  1.81it/s]
train:  46%|████▋     | 32/69 [00:17<00:21,  1.72it/s]
train:  48%|████▊     | 33/69 [00:18<00:22,  1.62it/s]
train:  49%|████▉     | 34/69 [00:19<00:20,  1.72it/s]
train:  51%|█████     | 35/69 [00:19<00:20,  1.68it/s]
train:  52%|█████▏    | 36/69 [00:20<00:18,  1.81it/s]
train:  54%|█████▎    | 37/69 [00:20<00:17,  1.80it/s]
train:  55%|█████▌    | 38/69 [00:21<00:16,  1.85it/s]
train:  57%|█████▋    | 39/69 [00:21<00:15,  1.92it/s]
train:  58%|█████▊    | 40/69 [00:22<00:14,  2.02it/s]
train:  59%|█████▉    | 41/69 [00:22<00:13,  2.03it/s]
train:  61%|██████    | 42/69 [00:23<00:12,  2.08it/s]
train:  62%|██████▏   | 43/69 [00:23<00:13,  1.94it/s]
train:  64%|██████▍   | 44/69 [00:24<00:13,  1.86it/s]
train:  65%|██████▌   | 45/69 [00:24<00:12,  1.88it/s]
train:  67%|██████▋   | 46/69 [00:25<00:12,  1.83it/s]
train:  68%|██████▊   | 47/69 [00:25<00:11,  1.87it/s]
train:  70%|██████▉   | 48/69 [00:26<00:10,  1.99it/s]
train:  71%|███████   | 49/69 [00:26<00:10,  1.92it/s]
train:  72%|███████▏  | 50/69 [00:27<00:09,  1.95it/s]
train:  74%|███████▍  | 51/69 [00:28<00:10,  1.73it/s]
train:  75%|███████▌  | 52/69 [00:28<00:09,  1.81it/s]
train:  77%|███████▋  | 53/69 [00:29<00:08,  1.88it/s]
train:  78%|███████▊  | 54/69 [00:29<00:08,  1.78it/s]
train:  80%|███████▉  | 55/69 [00:30<00:08,  1.75it/s]
train:  81%|████████  | 56/69 [00:30<00:07,  1.81it/s]
train:  83%|████████▎ | 57/69 [00:31<00:06,  1.93it/s]
train:  84%|████████▍ | 58/69 [00:31<00:05,  1.94it/s]
train:  86%|████████▌ | 59/69 [00:32<00:05,  1.99it/s]
train:  87%|████████▋ | 60/69 [00:32<00:04,  1.83it/s]
train:  88%|████████▊ | 61/69 [00:33<00:04,  1.88it/s]
train:  90%|████████▉ | 62/69 [00:34<00:04,  1.73it/s]
train:  91%|█████████▏| 63/69 [00:34<00:03,  1.84it/s]
train:  93%|█████████▎| 64/69 [00:35<00:02,  1.69it/s]
train:  94%|█████████▍| 65/69 [00:35<00:02,  1.76it/s]
train:  96%|█████████▌| 66/69 [00:36<00:01,  1.82it/s]
train:  97%|█████████▋| 67/69 [00:36<00:01,  1.97it/s]
train:  99%|█████████▊| 68/69 [00:37<00:00,  1.71it/s]
train: 100%|██████████| 69/69 [00:37<00:00,  1.90it/s]

d:\anaconda3\envs\pytorch\lib\site-packages\sklearn\metrics\_ranking.py:424: UndefinedMetricWarning: Only one class is present in y_true. ROC AUC score is not defined in that case.
  warnings.warn(
d:\anaconda3\envs\pytorch\lib\site-packages\sklearn\metrics\_ranking.py:424: UndefinedMetricWarning: Only one class is present in y_true. ROC AUC score is not defined in that case.
  warnings.warn(
d:\anaconda3\envs\pytorch\lib\site-packages\sklearn\metrics\_ranking.py:424: UndefinedMetricWarning: Only one class is present in y_true. ROC AUC score is not defined in that case.
  warnings.warn(
d:\anaconda3\envs\pytorch\lib\site-packages\sklearn\metrics\_ranking.py:424: UndefinedMetricWarning: Only one class is present in y_true. ROC AUC score is not defined in that case.
  warnings.warn(

extract features:   0%|          | 0/15 [00:00<?, ?it/s]
extract features:   7%|▋         | 1/15 [00:00<00:05,  2.44it/s]
extract features:  13%|█▎        | 2/15 [00:00<00:04,  3.22it/s]
extract features:  20%|██        | 3/15 [00:00<00:03,  3.52it/s]
extract features:  27%|██▋       | 4/15 [00:01<00:03,  2.90it/s]
extract features:  33%|███▎      | 5/15 [00:01<00:03,  2.89it/s]
extract features:  40%|████      | 6/15 [00:01<00:02,  3.01it/s]
extract features:  47%|████▋     | 7/15 [00:02<00:02,  3.15it/s]
extract features:  53%|█████▎    | 8/15 [00:02<00:02,  3.09it/s]
extract features:  60%|██████    | 9/15 [00:03<00:02,  2.73it/s]
extract features:  67%|██████▋   | 10/15 [00:03<00:01,  2.94it/s]
extract features:  73%|███████▎  | 11/15 [00:03<00:01,  2.78it/s]
extract features:  80%|████████  | 12/15 [00:04<00:00,  3.03it/s]
extract features:  87%|████████▋ | 13/15 [00:04<00:00,  2.96it/s]
extract features:  93%|█████████▎| 14/15 [00:04<00:00,  2.88it/s]
extract features: 100%|██████████| 15/15 [00:05<00:00,  2.84it/s]


Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]
Loading weights: 100%|██████████| 199/199 [00:00<00:00, 15890.24it/s]
[transformers] BertModel LOAD REPORT from: emilyalsentzer/Bio_ClinicalBERT
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
cls.seq_relationship.weight                | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.predictions.decoder.weight             | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.

train:   0%|          | 0/69 [00:00<?, ?it/s]
train:   1%|▏         | 1/69 [00:00<00:38,  1.76it/s]
train:   3%|▎         | 2/69 [00:01<00:36,  1.84it/s]
train:   4%|▍         | 3/69 [00:01<00:36,  1.82it/s]
train:   6%|▌         | 4/69 [00:02<00:36,  1.79it/s]
train:   7%|▋         | 5/69 [00:02<00:34,  1.88it/s]
train:   9%|▊         | 6/69 [00:03<00:34,  1.82it/s]
train:  10%|█         | 7/69 [00:03<00:33,  1.87it/s]
train:  12%|█▏        | 8/69 [00:04<00:34,  1.79it/s]
train:  13%|█▎        | 9/69 [00:05<00:35,  1.69it/s]
train:  14%|█▍        | 10/69 [00:05<00:33,  1.74it/s]
train:  16%|█▌        | 11/69 [00:06<00:32,  1.80it/s]
train:  17%|█▋        | 12/69 [00:06<00:30,  1.84it/s]
train:  19%|█▉        | 13/69 [00:07<00:30,  1.85it/s]
train:  20%|██        | 14/69 [00:07<00:29,  1.84it/s]
train:  22%|██▏       | 15/69 [00:08<00:28,  1.87it/s]
train:  23%|██▎       | 16/69 [00:08<00:28,  1.88it/s]
train:  25%|██▍       | 17/69 [00:09<00:28,  1.84it/s]
train:  26%|██▌       | 18/69 [00:09<00:27,  1.83it/s]
train:  28%|██▊       | 19/69 [00:10<00:26,  1.89it/s]
train:  29%|██▉       | 20/69 [00:10<00:24,  1.96it/s]
train:  30%|███       | 21/69 [00:11<00:26,  1.84it/s]
train:  32%|███▏      | 22/69 [00:11<00:25,  1.85it/s]
train:  33%|███▎      | 23/69 [00:12<00:25,  1.83it/s]
train:  35%|███▍      | 24/69 [00:13<00:25,  1.76it/s]
train:  36%|███▌      | 25/69 [00:13<00:24,  1.80it/s]
train:  38%|███▊      | 26/69 [00:14<00:23,  1.81it/s]
train:  39%|███▉      | 27/69 [00:14<00:22,  1.87it/s]
train:  41%|████      | 28/69 [00:15<00:21,  1.87it/s]
train:  42%|████▏     | 29/69 [00:15<00:19,  2.05it/s]
train:  43%|████▎     | 30/69 [00:16<00:20,  1.94it/s]
train:  45%|████▍     | 31/69 [00:16<00:20,  1.86it/s]
train:  46%|████▋     | 32/69 [00:17<00:21,  1.74it/s]
train:  48%|████▊     | 33/69 [00:18<00:22,  1.63it/s]
train:  49%|████▉     | 34/69 [00:18<00:20,  1.72it/s]
train:  51%|█████     | 35/69 [00:19<00:20,  1.68it/s]
train:  52%|█████▏    | 36/69 [00:19<00:18,  1.81it/s]
train:  54%|█████▎    | 37/69 [00:20<00:17,  1.79it/s]
train:  55%|█████▌    | 38/69 [00:20<00:16,  1.85it/s]
train:  57%|█████▋    | 39/69 [00:21<00:15,  1.99it/s]
train:  58%|█████▊    | 40/69 [00:21<00:13,  2.07it/s]
train:  59%|█████▉    | 41/69 [00:22<00:13,  2.05it/s]
train:  61%|██████    | 42/69 [00:22<00:12,  2.13it/s]
train:  62%|██████▏   | 43/69 [00:23<00:13,  2.00it/s]
train:  64%|██████▍   | 44/69 [00:23<00:12,  1.93it/s]
train:  65%|██████▌   | 45/69 [00:24<00:12,  1.93it/s]
train:  67%|██████▋   | 46/69 [00:24<00:12,  1.88it/s]
train:  68%|██████▊   | 47/69 [00:25<00:11,  1.92it/s]
train:  70%|██████▉   | 48/69 [00:25<00:10,  1.99it/s]
train:  71%|███████   | 49/69 [00:26<00:10,  1.89it/s]
train:  72%|███████▏  | 50/69 [00:26<00:09,  1.92it/s]
train:  74%|███████▍  | 51/69 [00:27<00:10,  1.73it/s]
train:  75%|███████▌  | 52/69 [00:28<00:09,  1.86it/s]
train:  77%|███████▋  | 53/69 [00:28<00:08,  1.95it/s]
train:  78%|███████▊  | 54/69 [00:29<00:08,  1.87it/s]
train:  80%|███████▉  | 55/69 [00:29<00:07,  1.84it/s]
train:  81%|████████  | 56/69 [00:30<00:06,  1.94it/s]
train:  83%|████████▎ | 57/69 [00:30<00:05,  2.06it/s]
train:  84%|████████▍ | 58/69 [00:30<00:05,  2.09it/s]
train:  86%|████████▌ | 59/69 [00:31<00:04,  2.14it/s]
train:  87%|████████▋ | 60/69 [00:32<00:04,  1.95it/s]
train:  88%|████████▊ | 61/69 [00:32<00:04,  2.00it/s]
train:  90%|████████▉ | 62/69 [00:33<00:03,  1.83it/s]
train:  91%|█████████▏| 63/69 [00:33<00:03,  1.93it/s]
train:  93%|█████████▎| 64/69 [00:34<00:02,  1.77it/s]
train:  94%|█████████▍| 65/69 [00:34<00:02,  1.86it/s]
train:  96%|█████████▌| 66/69 [00:35<00:01,  1.89it/s]
train:  97%|█████████▋| 67/69 [00:35<00:00,  2.03it/s]
train:  99%|█████████▊| 68/69 [00:36<00:00,  1.73it/s]
train: 100%|██████████| 69/69 [00:36<00:00,  1.94it/s]

d:\anaconda3\envs\pytorch\lib\site-packages\sklearn\metrics\_ranking.py:424: UndefinedMetricWarning: Only one class is present in y_true. ROC AUC score is not defined in that case.
  warnings.warn(
d:\anaconda3\envs\pytorch\lib\site-packages\sklearn\metrics\_ranking.py:424: UndefinedMetricWarning: Only one class is present in y_true. ROC AUC score is not defined in that case.
  warnings.warn(
d:\anaconda3\envs\pytorch\lib\site-packages\sklearn\metrics\_ranking.py:424: UndefinedMetricWarning: Only one class is present in y_true. ROC AUC score is not defined in that case.
  warnings.warn(
d:\anaconda3\envs\pytorch\lib\site-packages\sklearn\metrics\_ranking.py:424: UndefinedMetricWarning: Only one class is present in y_true. ROC AUC score is not defined in that case.
  warnings.warn(

extract features:   0%|          | 0/15 [00:00<?, ?it/s]
extract features:   7%|▋         | 1/15 [00:00<00:05,  2.54it/s]
extract features:  13%|█▎        | 2/15 [00:00<00:03,  3.31it/s]
extract features:  20%|██        | 3/15 [00:00<00:03,  3.58it/s]
extract features:  27%|██▋       | 4/15 [00:01<00:03,  2.94it/s]
extract features:  33%|███▎      | 5/15 [00:01<00:03,  2.95it/s]
extract features:  40%|████      | 6/15 [00:01<00:02,  3.09it/s]
extract features:  47%|████▋     | 7/15 [00:02<00:02,  3.25it/s]
extract features:  53%|█████▎    | 8/15 [00:02<00:02,  3.12it/s]
extract features:  60%|██████    | 9/15 [00:02<00:02,  2.99it/s]
extract features:  67%|██████▋   | 10/15 [00:03<00:01,  3.19it/s]
extract features:  73%|███████▎  | 11/15 [00:03<00:01,  3.02it/s]
extract features:  80%|████████  | 12/15 [00:03<00:00,  3.27it/s]
extract features:  87%|████████▋ | 13/15 [00:04<00:00,  3.04it/s]
extract features:  93%|█████████▎| 14/15 [00:04<00:00,  2.90it/s]
extract features: 100%|██████████| 15/15 [00:04<00:00,  2.81it/s]


Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]
Loading weights: 100%|██████████| 199/199 [00:00<00:00, 44223.08it/s]
[transformers] BertModel LOAD REPORT from: emilyalsentzer/Bio_ClinicalBERT
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
cls.seq_relationship.weight                | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.predictions.decoder.weight             | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.

train:   0%|          | 0/69 [00:00<?, ?it/s]
train:   1%|▏         | 1/69 [00:00<00:41,  1.62it/s]
train:   3%|▎         | 2/69 [00:01<00:37,  1.77it/s]
train:   4%|▍         | 3/69 [00:01<00:37,  1.78it/s]
train:   6%|▌         | 4/69 [00:02<00:36,  1.77it/s]
train:   7%|▋         | 5/69 [00:02<00:34,  1.86it/s]
train:   9%|▊         | 6/69 [00:03<00:34,  1.83it/s]
train:  10%|█         | 7/69 [00:03<00:32,  1.91it/s]
train:  12%|█▏        | 8/69 [00:04<00:33,  1.84it/s]
train:  13%|█▎        | 9/69 [00:04<00:33,  1.81it/s]
train:  14%|█▍        | 10/69 [00:05<00:31,  1.86it/s]
train:  16%|█▌        | 11/69 [00:06<00:31,  1.87it/s]
train:  17%|█▋        | 12/69 [00:06<00:29,  1.91it/s]
train:  19%|█▉        | 13/69 [00:07<00:29,  1.92it/s]
train:  20%|██        | 14/69 [00:07<00:28,  1.91it/s]
train:  22%|██▏       | 15/69 [00:08<00:27,  1.97it/s]
train:  23%|██▎       | 16/69 [00:08<00:26,  2.00it/s]
train:  25%|██▍       | 17/69 [00:08<00:25,  2.00it/s]
train:  26%|██▌       | 18/69 [00:09<00:25,  2.02it/s]
train:  28%|██▊       | 19/69 [00:09<00:23,  2.09it/s]

,model_family,text_col,output_dir,best_checkpoint,root_best_checkpoint,final_checkpoint,best_val_f1_macro,test_accuracy,test_macro_precision,test_macro_recall,test_macro_f1,test_weighted_precision,test_weighted_recall,test_weighted_f1,test_loss,test_macro_auc_ovr,test_weighted_auc_ovr,test_macro_auc,test_weighted_auc,test_auc,test_precision_macro,test_recall_macro,test_f1_macro,test_precision_weighted,test_recall_weighted,test_f1_weighted,source_file
0,mobilevit_concat,text_full,D:\Deep Learning\output_concat_demo\02_closed_...,D:\Deep Learning\output_concat_demo\02_closed_...,D:\Deep Learning\output_concat_demo\02_closed_...,D:\Deep Learning\output_concat_demo\02_closed_...,0.37297,0.682203,0.350401,0.490714,0.407304,0.499086,0.682203,0.57526,0.929167,NaN,0.871782,NaN,0.871782,NaN,0.350401,0.490714,0.407304,0.499086,0.682203,0.57526,D:\Deep Learning\output_concat_demo\02_closed_...

------------------------------------------------------------------------------------------------------------------------
mobilevit_concat | text_full | target=ISIC 2019
------------------------------------------------------------------------------------------------------------------------

========================================================================================================================
d:\anaconda3\envs\pytorch\python.exe -m src.evaluate_closed_set_transfer --standardized-csv D:\Deep Learning\output_concat_demo\standardized\all_preprocessed_splits_standardized_text.csv --target-dataset ISIC 2019 --target-image-roots D:\Deep Learning\ISIC_2019_Training_Input D:\Deep Learning\ISIC_2019_Test_Input --checkpoint D:\Deep Learning\output_concat_demo\02_closed_set\mobilevit_concat\text_full\best.pt --output-dir D:\Deep Learning\output_concat_demo\03_direct_transfer --model-family mobilevit_concat --text-col text_full --batch-size 16
========================================================================================================================

STDOUT:
Saved direct closed-set transfer outputs to D:\Deep Learning\output_concat_demo\03_direct_transfer\mobilevit_concat\text_full\ISIC_2019\direct_closed_set_transfer


STDERR:
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]
Loading weights: 100%|██████████| 199/199 [00:00<00:00, 39827.58it/s]
[transformers] BertModel LOAD REPORT from: emilyalsentzer/Bio_ClinicalBERT
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
cls.predictions.bias                       | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
cls.predictions.decoder.weight             | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
d:\anaconda3\envs\pytorch\lib\site-packages\sklearn\metrics\_ranking.py:424: UndefinedMetricWarning: Only one class is present in y_true. ROC AUC score is not defined in that case.
  warnings.warn(
d:\anaconda3\envs\pytorch\lib\site-packages\sklearn\metrics\_ranking.py:424: UndefinedMetricWarning: Only one class is present in y_true. ROC AUC score is not defined in that case.
  warnings.warn(
d:\anaconda3\envs\pytorch\lib\site-packages\sklearn\metrics\_ranking.py:424: UndefinedMetricWarning: Only one class is present in y_true. ROC AUC score is not defined in that case.
  warnings.warn(
d:\anaconda3\envs\pytorch\lib\site-packages\sklearn\metrics\_ranking.py:424: UndefinedMetricWarning: Only one class is present in y_true. ROC AUC score is not defined in that case.
  warnings.warn(


========================================================================================================================
d:\anaconda3\envs\pytorch\python.exe -m src.train_dann --standardized-csv D:\Deep Learning\output_concat_demo\standardized\all_preprocessed_splits_standardized_text.csv --source-dataset PAD-UFES-20 --target-dataset ISIC 2019 --source-image-roots D:\Deep Learning\images --target-image-roots D:\Deep Learning\ISIC_2019_Training_Input D:\Deep Learning\ISIC_2019_Test_Input --checkpoint D:\Deep Learning\output_concat_demo\02_closed_set\mobilevit_concat\text_full\best.pt --output-dir D:\Deep Learning\output_concat_demo\04_dann --model-family mobilevit_concat --text-col text_full --batch-size 16 --epochs 1 --energy-temperature 1.0
========================================================================================================================

STDOUT:
{'epoch': 1, 'dann_loss': 2.252772617943679, 'class_loss': 0.9603625460516049, 'domain_loss': 1.2924100734010529, 'n_steps': 79, 'target_val_known_accuracy': 0.20980187695516161, 'target_val_known_macro_precision': 0.14916483717526527, 'target_val_known_macro_recall': 0.23314159292035397, 'target_val_known_macro_f1': 0.12275229004968224, 'target_val_known_weighted_precision': 0.11298836928026397, 'target_val_known_weighted_recall': 0.20980187695516161, 'target_val_known_weighted_f1': 0.10106211412146175, 'target_val_known_loss': 1.7201666053136189, 'target_val_known_macro_auc_ovr': nan, 'target_val_known_weighted_auc_ovr': 0.5492144645198747, 'target_val_known_macro_auc': nan, 'target_val_known_weighted_auc': 0.5492144645198747, 'target_val_known_auc': nan, 'target_val_known_precision_macro': 0.14916483717526527, 'target_val_known_recall_macro': 0.23314159292035397, 'target_val_known_f1_macro': 0.12275229004968224, 'target_val_known_precision_weighted': 0.11298836928026397, 'target_val_known_recall_weighted': 0.20980187695516161, 'target_val_known_f1_weighted': 0.10106211412146175, 'lr': 0.0001}
Saved DANN outputs to D:\Deep Learning\output_concat_demo\04_dann\mobilevit_concat\text_full\ISIC_2019


STDERR:
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]
Loading weights: 100%|██████████| 199/199 [00:00<00:00, 36143.70it/s]
[transformers] BertModel LOAD REPORT from: emilyalsentzer/Bio_ClinicalBERT
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
cls.predictions.decoder.weight             | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
d:\anaconda3\envs\pytorch\lib\site-packages\sklearn\metrics\_ranking.py:424: UndefinedMetricWarning: Only one class is present in y_true. ROC AUC score is not defined in that case.
  warnings.warn(
d:\anaconda3\envs\pytorch\lib\site-packages\sklearn\metrics\_ranking.py:424: UndefinedMetricWarning: Only one class is present in y_true. ROC AUC score is not defined in that case.
  warnings.warn(
d:\anaconda3\envs\pytorch\lib\site-packages\sklearn\metrics\_ranking.py:424: UndefinedMetricWarning: Only one class is present in y_true. ROC AUC score is not defined in that case.
  warnings.warn(
d:\anaconda3\envs\pytorch\lib\site-packages\sklearn\metrics\_ranking.py:424: UndefinedMetricWarning: Only one class is present in y_true. ROC AUC score is not defined in that case.
  warnings.warn(

dann:   0%|          | 0/79 [00:00<?, ?it/s]
dann:   1%|▏         | 1/79 [00:01<01:32,  1.18s/it]
dann:   3%|▎         | 2/79 [00:02<01:27,  1.13s/it]
dann:   4%|▍         | 3/79 [00:03<01:22,  1.09s/it]
dann:   5%|▌         | 4/79 [00:04<01:23,  1.11s/it]
dann:   6%|▋         | 5/79 [00:05<01:19,  1.07s/it]
dann:   8%|▊         | 6/79 [00:06<01:14,  1.03s/it]
dann:   9%|▉         | 7/79 [00:07<01:12,  1.00s/it]
dann:  10%|█         | 8/79 [00:08<01:12,  1.02s/it]
dann:  11%|█▏        | 9/79 [00:09<01:09,  1.01it/s]
dann:  13%|█▎        | 10/79 [00:10<01:09,  1.00s/it]
dann:  14%|█▍        | 11/79 [00:11<01:09,  1.02s/it]
dann:  15%|█▌        | 12/79 [00:12<01:10,  1.05s/it]
dann:  16%|█▋        | 13/79 [00:13<01:08,  1.04s/it]
dann:  18%|█▊        | 14/79 [00:14<01:12,  1.11s/it]
dann:  19%|█▉        | 15/79 [00:15<01:08,  1.07s/it]
dann:  20%|██        | 16/79 [00:16<01:09,  1.10s/it]
dann:  22%|██▏       | 17/79 [00:17<01:06,  1.07s/it]
dann:  23%|██▎       | 18/79 [00:19<01:04,  1.06s/it]
dann:  24%|██▍       | 19/79 [00:20<01:04,  1.07s/it]
dann:  25%|██▌       | 20/79 [00:21<01:04,  1.09s/it]
dann:  27%|██▋       | 21/79 [00:22<01:03,  1.10s/it]
dann:  28%|██▊       | 22/79 [00:23<01:02,  1.10s/it]
dann:  29%|██▉       | 23/79 [00:24<00:59,  1.07s/it]
dann:  30%|███       | 24/79 [00:25<00:59,  1.09s/it]
dann:  32%|███▏      | 25/79 [00:26<01:01,  1.13s/it]
dann:  33%|███▎      | 26/79 [00:27<01:00,  1.13s/it]
dann:  34%|███▍      | 27/79 [00:28<00:55,  1.07s/it]
dann:  35%|███▌      | 28/79 [00:30<00:55,  1.09s/it]
dann:  37%|███▋      | 29/79 [00:30<00:52,  1.05s/it]
dann:  38%|███▊      | 30/79 [00:32<00:52,  1.07s/it]
dann:  39%|███▉      | 31/79 [00:33<00:50,  1.04s/it]
dann:  41%|████      | 32/79 [00:34<00:47,  1.02s/it]
dann:  42%|████▏     | 33/79 [00:35<00:46,  1.02s/it]
dann:  43%|████▎     | 34/79 [00:35<00:44,  1.02it/s]
dann:  44%|████▍     | 35/79 [00:37<00:46,  1.07s/it]
dann:  46%|████▌     | 36/79 [00:38<00:45,  1.07s/it]
dann:  47%|████▋     | 37/79 [00:39<00:44,  1.05s/it]
dann:  48%|████▊     | 38/79 [00:40<00:43,  1.07s/it]
dann:  49%|████▉     | 39/79 [00:41<00:42,  1.07s/it]
dann:  51%|█████     | 40/79 [00:42<00:42,  1.10s/it]
dann:  52%|█████▏    | 41/79 [00:43<00:41,  1.09s/it]
dann:  53%|█████▎    | 42/79 [00:44<00:41,  1.12s/it]
dann:  54%|█████▍    | 43/79 [00:45<00:39,  1.09s/it]
dann:  56%|█████▌    | 44/79 [00:47<00:38,  1.09s/it]
dann:  57%|█████▋    | 45/79 [00:48<00:37,  1.11s/it]
dann:  58%|█████▊    | 46/79 [00:49<00:35,  1.08s/it]
dann:  59%|█████▉    | 47/79 [00:50<00:33,  1.05s/it]
dann:  61%|██████    | 48/79 [00:51<00:32,  1.04s/it]
dann:  62%|██████▏   | 49/79 [00:52<00:30,  1.03s/it]
dann:  63%|██████▎   | 50/79 [00:53<00:29,  1.01s/it]
dann:  65%|██████▍   | 51/79 [00:54<00:27,  1.02it/s]
dann:  66%|██████▌   | 52/79 [00:54<00:25,  1.05it/s]
dann:  67%|██████▋   | 53/79 [00:55<00:25,  1.04it/s]
dann:  68%|██████▊   | 54/79 [00:57<00:25,  1.00s/it]
dann:  70%|██████▉   | 55/79 [00:58<00:24,  1.01s/it]
dann:  71%|███████   | 56/79 [00:59<00:23,  1.02s/it]
dann:  72%|███████▏  | 57/79 [01:00<00:23,  1.06s/it]
dann:  73%|███████▎  | 58/79 [01:01<00:23,  1.10s/it]
dann:  75%|███████▍  | 59/79 [01:02<00:21,  1.07s/it]
dann:  76%|███████▌  | 60/79 [01:03<00:20,  1.08s/it]
dann:  77%|███████▋  | 61/79 [01:04<00:19,  1.10s/it]
dann:  78%|███████▊  | 62/79 [01:05<00:18,  1.08s/it]
dann:  80%|███████▉  | 63/79 [01:06<00:16,  1.04s/it]
dann:  81%|████████  | 64/79 [01:07<00:15,  1.01s/it]
dann:  82%|████████▏ | 65/79 [01:08<00:13,  1.00it/s]
dann:  84%|████████▎ | 66/79 [01:09<00:12,  1.01it/s]
dann:  85%|████████▍ | 67/79 [01:10<00:11,  1.03it/s]
dann:  86%|████████▌ | 68/79 [01:11<00:10,  1.01it/s]
dann:  87%|████████▋ | 69/79 [01:12<00:09,  1.00it/s]
dann:  89%|████████▊ | 70/79 [01:13<00:08,  1.04it/s]
dann:  90%|████████▉ | 71/79 [01:14<00:07,  1.07it/s]
dann:  91%|█████████ | 72/79 [01:15<00:06,  1.05it/s]
dann:  92%|█████████▏| 73/79 [01:16<00:05,  1.09it/s]
dann:  94%|█████████▎| 74/79 [01:17<00:04,  1.09it/s]
dann:  95%|█████████▍| 75/79 [01:17<00:03,  1.09it/s]
dann:  96%|█████████▌| 76/79 [01:18<00:02,  1.09it/s]
dann:  97%|█████████▋| 77/79 [01:19<00:01,  1.07it/s]
dann:  99%|█████████▊| 78/79 [01:20<00:00,  1.07it/s]
dann: 100%|██████████| 79/79 [01:21<00:00,  1.21it/s]

d:\anaconda3\envs\pytorch\lib\site-packages\sklearn\metrics\_ranking.py:424: UndefinedMetricWarning: Only one class is present in y_true. ROC AUC score is not defined in that case.
  warnings.warn(
d:\anaconda3\envs\pytorch\lib\site-packages\sklearn\metrics\_ranking.py:424: UndefinedMetricWarning: Only one class is present in y_true. ROC AUC score is not defined in that case.
  warnings.warn(
d:\anaconda3\envs\pytorch\lib\site-packages\sklearn\metrics\_ranking.py:424: UndefinedMetricWarning: Only one class is present in y_true. ROC AUC score is not defined in that case.
  warnings.warn(
d:\anaconda3\envs\pytorch\lib\site-packages\sklearn\metrics\_ranking.py:424: UndefinedMetricWarning: Only one class is present in y_true. ROC AUC score is not defined in that case.
  warnings.warn(
d:\anaconda3\envs\pytorch\lib\site-packages\sklearn\metrics\_ranking.py:424: UndefinedMetricWarning: Only one class is present in y_true. ROC AUC score is not defined in that case.
  warnings.warn(
d:\anaconda3\envs\pytorch\lib\site-packages\sklearn\metrics\_ranking.py:424: UndefinedMetricWarning: Only one class is present in y_true. ROC AUC score is not defined in that case.
  warnings.warn(

collect:   0%|          | 0/342 [00:00<?, ?it/s]
collect:   0%|          | 1/342 [00:00<01:03,  5.37it/s]
collect:   1%|          | 2/342 [00:00<01:02,  5.46it/s]
collect:   1%|          | 3/342 [00:00<01:01,  5.49it/s]
collect:   1%|          | 4/342 [00:00<00:59,  5.68it/s]
collect:   1%|▏         | 5/342 [00:00<00:58,  5.73it/s]
collect:   2%|▏         | 6/342 [00:01<00:57,  5.84it/s]
collect:   2%|▏         | 7/342 [00:01<00:57,  5.85it/s]
collect:   2%|▏         | 8/342 [00:01<00:58,  5.67it/s]
collect:   3%|▎         | 9/342 [00:01<00:59,  5.64it/s]
collect:   3%|▎         | 10/342 [00:01<00:58,  5.67it/s]
collect:   3%|▎         | 11/342 [00:01<01:00,  5.43it/s]
collect:   4%|▎         | 12/342 [00:02<00:59,  5.54it/s]
collect:   4%|▍         | 13/342 [00:02<00:59,  5.54it/s]
collect:   4%|▍         | 14/342 [00:02<00:59,  5.55it/s]
collect:   4%|▍         | 15/342 [00:02<00:58,  5.60it/s]
collect:   5%|▍         | 16/342 [00:02<00:58,  5.54it/s]
collect:   5%|▍         | 17/342 [00:03<00:59,  5.45it/s]
collect:   5%|▌         | 18/342 [00:03<01:00,  5.35it/s]
collect:   6%|▌         | 19/342 [00:03<00:58,  5.48it/s]
collect:   6%|▌         | 20/342 [00:03<00:57,  5.62it/s]
collect:   6%|▌         | 21/342 [00:03<00:56,  5.68it/s]
collect:   6%|▋         | 22/342 [00:03<00:56,  5.68it/s]
collect:   7%|▋         | 23/342 [00:04<00:56,  5.66it/s]
collect:   7%|▋         | 24/342 [00:04<00:57,  5.49it/s]
collect:   7%|▋         | 25/342 [00:04<00:57,  5.52it/s]
collect:   8%|▊         | 26/342 [00:04<00:59,  5.34it/s]
collect:   8%|▊         | 27/342 [00:04<01:00,  5.18it/s]
collect:   8%|▊         | 28/342 [00:05<01:00,  5.16it/s]
collect:   8%|▊         | 29/342 [00:05<00:58,  5.39it/s]
collect:   9%|▉         | 30/342 [00:05<00:55,  5.58it/s]
collect:   9%|▉         | 31/342 [00:05<00:57,  5.41it/s]
collect:   9%|▉         | 32/342 [00:05<00:58,  5.34it/s]
collect:  10%|▉         | 33/342 [00:05<00:55,  5.54it/s]
collect:  10%|▉         | 34/342 [00:06<00:55,  5.51it/s]
collect:  10%|█         | 35/342 [00:06<00:54,  5.61it/s]
collect:  11%|█         | 36/342 [00:06<00:54,  5.67it/s]
collect:  11%|█         | 37/342 [00:06<00:55,  5.50it/s]
collect:  11%|█         | 38/342 [00:06<00:55,  5.45it/s]
collect:  11%|█▏        | 39/342 [00:07<00:55,  5.43it/s]
collect:  12%|█▏        | 40/342 [00:07<00:55,  5.43it/s]
collect:  12%|█▏        | 41/342 [00:07<00:55,  5.39it/s]
collect:  12%|█▏        | 42/342 [00:07<00:54,  5.48it/s]
collect:  13%|█▎        | 43/342 [00:07<00:54,  5.48it/s]
collect:  13%|█▎        | 44/342 [00:07<00:54,  5.44it/s]
collect:  13%|█▎        | 45/342 [00:08<00:55,  5.39it/s]
collect:  13%|█▎        | 46/342 [00:08<00:56,  5.23it/s]
collect:  14%|█▎        | 47/342 [00:08<00:55,  5.31it/s]
collect:  14%|█▍        | 48/342 [00:08<00:54,  5.36it/s]
collect:  14%|█▍        | 49/342 [00:08<00:53,  5.46it/s]
collect:  15%|█▍        | 50/342 [00:09<00:54,  5.33it/s]
collect:  15%|█▍        | 51/342 [00:09<00:55,  5.20it/s]
collect:  15%|█▌        | 52/342 [00:09<00:54,  5.34it/s]
collect:  15%|█▌        | 53/342 [00:09<00:51,  5.60it/s]
collect:  16%|█▌        | 54/342 [00:09<00:50,  5.68it/s]
collect:  16%|█▌        | 55/342 [00:10<00:51,  5.58it/s]
collect:  16%|█▋        | 56/342 [00:10<00:49,  5.83it/s]
collect:  17%|█▋        | 57/342 [00:10<00:49,  5.72it/s]
collect:  17%|█▋        | 58/342 [00:10<00:48,  5.83it/s]
collect:  17%|█▋        | 59/342 [00:10<00:48,  5.85it/s]
collect:  18%|█▊        | 60/342 [00:10<00:49,  5.69it/s]
collect:  18%|█▊        | 61/342 [00:11<00:49,  5.67it/s]
collect:  18%|█▊        | 62/342 [00:11<00:49,  5.63it/s]
collect:  18%|█▊        | 63/342 [00:11<00:49,  5.59it/s]
collect:  19%|█▊        | 64/342 [00:11<00:51,  5.42it/s]
collect:  19%|█▉        | 65/342 [00:11<00:52,  5.27it/s]
collect:  19%|█▉        | 66/342 [00:12<00:53,  5.20it/s]
collect:  20%|█▉        | 67/342 [00:12<00:56,  4.89it/s]
collect:  20%|█▉        | 68/342 [00:12<00:56,  4.85it/s]
collect:  20%|██        | 69/342 [00:12<00:57,  4.75it/s]
collect:  20%|██        | 70/342 [00:12<00:54,  4.99it/s]
collect:  21%|██        | 71/342 [00:13<00:51,  5.21it/s]
collect:  21%|██        | 72/342 [00:13<00:50,  5.32it/s]
collect:  21%|██▏       | 73/342 [00:13<00:50,  5.37it/s]
collect:  22%|██▏       | 74/342 [00:13<00:50,  5.33it/s]
collect:  22%|██▏       | 75/342 [00:13<00:50,  5.27it/s]
collect:  22%|██▏       | 76/342 [00:13<00:50,  5.23it/s]
collect:  23%|██▎       | 77/342 [00:14<00:51,  5.19it/s]
collect:  23%|██▎       | 78/342 [00:14<00:50,  5.25it/s]
collect:  23%|██▎       | 79/342 [00:14<00:51,  5.15it/s]
collect:  23%|██▎       | 80/342 [00:14<00:50,  5.20it/s]
collect:  24%|██▎       | 81/342 [00:14<00:49,  5.31it/s]
collect:  24%|██▍       | 82/342 [00:15<00:51,  5.08it/s]
collect:  24%|██▍       | 83/342 [00:15<00:48,  5.31it/s]
collect:  25%|██▍       | 84/342 [00:15<00:49,  5.22it/s]
collect:  25%|██▍       | 85/342 [00:15<00:48,  5.29it/s]
collect:  25%|██▌       | 86/342 [00:15<00:48,  5.33it/s]
collect:  25%|██▌       | 87/342 [00:16<00:46,  5.44it/s]
collect:  26%|██▌       | 88/342 [00:16<00:45,  5.54it/s]
collect:  26%|██▌       | 89/342 [00:16<00:43,  5.78it/s]
collect:  26%|██▋       | 90/342 [00:16<00:45,  5.58it/s]
collect:  27%|██▋       | 91/342 [00:16<00:46,  5.44it/s]
collect:  27%|██▋       | 92/342 [00:16<00:45,  5.44it/s]
collect:  27%|██▋       | 93/342 [00:17<00:45,  5.45it/s]
collect:  27%|██▋       | 94/342 [00:17<00:46,  5.36it/s]
collect:  28%|██▊       | 95/342 [00:17<00:45,  5.43it/s]
collect:  28%|██▊       | 96/342 [00:17<00:45,  5.42it/s]
collect:  28%|██▊       | 97/342 [00:17<00:44,  5.48it/s]
collect:  29%|██▊       | 98/342 [00:18<00:45,  5.41it/s]
collect:  29%|██▉       | 99/342 [00:18<00:42,  5.68it/s]
collect:  29%|██▉       | 100/342 [00:18<00:42,  5.68it/s]
collect:  30%|██▉       | 101/342 [00:18<00:41,  5.77it/s]
collect:  30%|██▉       | 102/342 [00:18<00:43,  5.49it/s]
collect:  30%|███       | 103/342 [00:18<00:43,  5.46it/s]
collect:  30%|███       | 104/342 [00:19<00:45,  5.24it/s]
collect:  31%|███       | 105/342 [00:19<00:45,  5.27it/s]
collect:  31%|███       | 106/342 [00:19<00:47,  4.99it/s]
collect:  31%|███▏      | 107/342 [00:19<00:45,  5.21it/s]
collect:  32%|███▏      | 108/342 [00:19<00:45,  5.16it/s]
collect:  32%|███▏      | 109/342 [00:20<00:44,  5.27it/s]
collect:  32%|███▏      | 110/342 [00:20<00:42,  5.47it/s]
collect:  32%|███▏      | 111/342 [00:20<00:43,  5.36it/s]
collect:  33%|███▎      | 112/342 [00:20<00:42,  5.47it/s]
collect:  33%|███▎      | 113/342 [00:20<00:41,  5.57it/s]
collect:  33%|███▎      | 114/342 [00:20<00:41,  5.55it/s]
collect:  34%|███▎      | 115/342 [00:21<00:41,  5.50it/s]
collect:  34%|███▍      | 116/342 [00:21<00:40,  5.53it/s]
collect:  34%|███▍      | 117/342 [00:21<00:40,  5.61it/s]
collect:  35%|███▍      | 118/342 [00:21<00:39,  5.61it/s]
collect:  35%|███▍      | 119/342 [00:21<00:41,  5.38it/s]
collect:  35%|███▌      | 120/342 [00:22<00:39,  5.57it/s]
collect:  35%|███▌      | 121/342 [00:22<00:39,  5.63it/s]
collect:  36%|███▌      | 122/342 [00:22<00:37,  5.79it/s]
collect:  36%|███▌      | 123/342 [00:22<00:37,  5.78it/s]
collect:  36%|███▋      | 124/342 [00:22<00:39,  5.55it/s]
collect:  37%|███▋      | 125/342 [00:22<00:38,  5.62it/s]
collect:  37%|███▋      | 126/342 [00:23<00:39,  5.44it/s]

In [ ]:
from pathlib import Path
import ast
import re

SRC = Path(r"D:/Deep Learning/skin_lesion_openworld/skin_lesion_openworld/src")

def get_config_fields():
    tree = ast.parse((SRC / "config.py").read_text(encoding="utf-8"))
    fields = []
    for node in tree.body:
        if isinstance(node, ast.ClassDef) and node.name == "ExperimentConfig":
            for item in node.body:
                if isinstance(item, ast.AnnAssign) and isinstance(item.target, ast.Name):
                    fields.append(item.target.id)
    return fields

config_fields = set(get_config_fields())

required_config_fields = {
    "num_workers",
    "image_model_name",
    "resnet_model_name",
    "text_model_name",
    "max_text_len",
    "patience",
    "lr",
    "weight_decay",
    "scheduler_factor",
    "scheduler_patience",
    "fusion_dim",
    "num_heads",
    "balance_beta",
    "use_soft_weighted_sampler",
    "use_weighted_loss",
    "domain_loss_weight",
    "dann_lambda_max",
    "energy_temperature",
    "freeze_backbones",
}

print("Missing config fields:")
print(sorted(required_config_fields - config_fields))

for filename in [
    "models.py",
    "train_closed_set.py",
    "train_dann.py",
    "evaluate_openworld.py",
    "evaluate_closed_set_transfer.py",
    "tune_hyperparameters.py",
]:
    text = (SRC / filename).read_text(encoding="utf-8")
    print("\n", filename)
    print("  mobilevit_concat:", "mobilevit_concat" in text)
    print("  resnet50_concat:", "resnet50_concat" in text)
    print("  freeze_backbones refs:", text.count("freeze_backbones"))
    print("  dropout refs:", text.count("dropout"))

# Specific energy-threshold issue in evaluate_openworld.py
openworld_text = (SRC / "evaluate_openworld.py").read_text(encoding="utf-8")
print("\nEnergy threshold clamp problem:")
print("  clamps to [0, 1]:", "candidates >= 0.0" in openworld_text and "candidates <= 1.0" in openworld_text)

# Part B — ResNet50 concatenation

This block performs the same complete demonstration using `resnet50_concat`.

In [ ]:
# validate_project_files()
run_full_concat_pipeline("resnet50_concat")

## 12. Final comparison: MobileViT concat vs ResNet50 concat

In [ ]:
def compare_open_world_models():
    rows = []

    for model_family in ["mobilevit_concat", "resnet50_concat"]:
        root = OPENWORLD_OUT / model_family
        json_df = collect_json_metrics(root, ["*metrics*.json", "openworld_metrics.json"])

        if json_df.empty:
            continue

        json_df["model_family"] = model_family
        rows.append(json_df)

    if not rows:
        print("No open-world metrics found for comparison yet.")
        return pd.DataFrame()

    df = pd.concat(rows, ignore_index=True, sort=False)

    metric_cols = [
        c for c in df.columns
        if any(key in c for key in [
            "open_macro_f1",
            "open_weighted_f1",
            "unknown_auroc",
            "unknown_recall",
            "unknown_f1",
            "oscr",
            "threshold",
            "scoring_method",
        ])
    ]

    display_cols = ["model_family", "source_file", *metric_cols]
    display(df[display_cols].head(100))

    return df

comparison_df = compare_open_world_models()

## 13. Presentation notes

For a quick live demonstration, reduce runtime first:

```python
N_TRIALS = 2
TRIAL_EPOCHS = 1
CLOSED_SET_EPOCHS = 1
DANN_EPOCHS = 1
```

Then set:

```python
RUN_COMMANDS = True
```

For final experiments, increase trials and epochs again.